### PR TITLE
CSS: fixed #1062; fixed #1063; Added flex support

### LINKED ISSUE #1062: Add all "CSS Legal Color Values" to komodo
Currently komodo only supports rgb and hex, would be nice to have [all](http://www.w3schools.com/cssref/css_colors_legal.asp) color value's in the autocompletion.
```javascript
#
rgb(
rgba(
hsl(
hsla(
```

### LINKED ISSUE #1063: Add support for the flexbox modal
Another enhancement request, currently i get no auto completion when working with the [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)(the [future](http://www.sitepoint.com/responsive-fluid-width-variable-item-navigation-css/#the-future-flexbox) is almost [here](http://caniuse.com/#search=flexbox)) modal.

### PR DESCRIPTION
**Pull request by Defman21**
CSS: fixed #1062; fixed #1063; Added flex support, all available color ranges has been added (rgba, hsl, hsla)

### CODE REVIEW

**Comment by mitchell-as** [comment]
Thanks for your hard work! Please note the CSS color completions should be in alphabetic order before I can accept the PR. Please re-order them.

**Comment by Defman21** [comment]
Okay, i'll do that :)

**Comment by Defman21** [comment]
I did it.

**Comment by Naatan** [comment]
Do you type (copy/paste) these out manually @Defman21 ?

**Comment by Defman21** [comment]
Yeah.

**Comment by Naatan** [comment]
My hat goes off to you.

**Comment by Defman21** [comment]
I was doing the same for CSS3 codeintel.. hehe

**Comment by Defman21** [comment]
Should I merge the commits into one?

**Comment by Naatan** [comment]
4 commits is manageable. Still the answer to the question "would you prefer I merge these commits" will almost always be yes :)

**Comment by Defman21** [comment]
Merged.

**Comment by tonyattwood** [comment]
Hey,

Take a look at this stuff,  it's so funny! I coudn't stop laughing, read it here  <http://fair.247oracle.com/e4cympe>

tony.attwood@ntlworld.com

**Pull request merged**
