### PR TITLE
correctly resolve methods returning "$this"

### PR DESCRIPTION
**Pull request by wizza-smile**
resolves this issue:
https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/477

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks @wizza-smile - this looks great! Note we are currently very busy putting the final touches on Komodo 9.0 final, once that's done we'll be sure to review this PR!

**Comment by Defman21** [comment]
Please merge it! :+1:

**Comment by Naatan** [comment]
Will definitely merge this once I have had time to review, probably next week :)

**Comment by Defman21** [comment]
I tested that. Works fine :+1: 
```php
class MyClass {
  
  public function obj() {
    return $this;
  }
  
  public function obj2() {
    return $this->obj();
  }
  
  public function call() {
    echo "Called";
  }
}

$obj = new MyClass();
$obj->{auto-complete works}obj2()->{auto-complete works}obj()->{auto-complete works}call();
```

**Comment by mitchell-as** [comment]
Unit tests here: https://github.com/Komodo/KomodoEdit/commit/fb34ee1f251cb426d280926b3f9d62a2a33d5344

**Pull request merged**
