### PR TITLE
Commando: Files Scope: added open in places item, fixes #2401

### LINKED ISSUE #2401: open folder in Place from commando
Provide a menu option to open a folder in Places as the root folder.

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Defman21** [comment]
I'll say when it's complete :)

**Comment by Naatan** [comment]
Will try/review when I can :) thanks for contributing! Now we need one that just highlights the folder in Places *hint* ;)

**Comment by Defman21** [comment]
If there's such an API, I'll implement that 🙂

**Comment by Naatan** [comment]
`ko.places.manager.showTreeItemByFile(URI);`

**Comment by Defman21** [comment]
Aha, thanks.

**Comment by Defman21** [comment]
Done. Just correct strings because i ain't good at naming features :P

**Comment by Naatan** [comment]
Nearly there, can you remove the `navBack()` from both items? That doesn't feel right here.

**Comment by Defman21** [comment]
Yep.

**Comment by Defman21** [comment]
Daym.

**Comment by Naatan** [comment]
Thanks @Defman21 !

**Pull request merged**
