### PR TITLE
added css region folding

### PR DESCRIPTION
**Pull request by babobski**
added the region folding as descibed here #715 for css.(now from a fresh fork)

### CODE REVIEW

**Comment by mitchell-as** [comment]
Thanks so much!

**Comment by mitchell-as** [comment]
Hmm, I had to revert the PR because the CSS lexer will no longer compile.  I'm not sure why this is the case, but I cannot look into it for a while until 9.3 is out the door.

Were you able to get your changes to compile?

**Comment by Defman21** [comment]
If you're not be able to compile your changes @babobski, leave it to me. I want to dig in it :)

**Comment by babobski** [comment]
No I didn't compile komodo (I'm not that experienced with komodo), just added the change to the lexer, looked add the examples above and added a regex for folding the css regions.
@Defman21 if you can look in to this, it would be appreciated :thumbsup:

**Comment by Defman21** [comment]
Seems like CSS_OPERATOR does not support regex.

**Comment by Defman21** [comment]
`fold` does not support Regex, you should write a complete statement for that.

**Comment by babobski** [comment]
@Defman21 thanks for looking in to this, i saw your [commit](https://github.com/Defman21/KomodoEdit/commit/0060b4c5b3b346eccfe0b0efb40e243fbc73440c), so something like this would work?
```javascript
fold "/* #region RegionName */" SSL_COMMENT
fold "/* #region RegionName */" SSL_COMMENT
```

**Comment by Defman21** [comment]
No.

**Comment by Defman21** [comment]
1. There must be no spaces.
2. The fold string should be "/*region", else it won't work if there is a name for this region. (`/*region MyRegion*/)
3. SSL_* is not supported in CSS lexer. It should be CSS_COMMENT.
4. CSS lexer does not support _COMMENTBLOCK, so seems like there's no way to implement this feature. I'm not sure you can use CSS_OPERATOR for that (I'll try).

**Comment by babobski** [comment]
Yeah sorry,  I'm currently not that familiar with [UDL's](http://www.activestate.com/blog/2007/01/adding-new-languages-komodo-udl).
And this one was a bit sloppy of me
> SSL_* is not supported in CSS lexer. It should be CSS_COMMENT.

had someone over and in the rush i didn't investigate that part.
But if you can check if it's possible with the CSS_OPERATOR it would be great.

**Pull request merged**
