### PR TITLE
Ruby: Lint: added Rubocop linter

### LINKED ISSUE #2287: Rubocop integration
### Short Summary

Rubocop is pep8 in Ruby world, and I'd want to see it in Komodo :)

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

fixed #2287

### CODE REVIEW

**Comment by Defman21** [comment]
I've added a checkbox that allows to disable Rubocop linter:

image

**Comment by Defman21** [comment]
Hmm, there's a bug that built-in linting doesn't work. I'll fix it.

**Comment by Defman21** [comment]
PR status: ready for merge. It works fine :)

If you want me to change the localization strings, let me know.

**Comment by Naatan** [comment]
Awesome work, thanks @Defman21 ! :)

**Comment by Defman21** [comment]
@Naatan I assume your points from https://github.com/Komodo/KomodoEdit/pull/2656 applies to this PR as well? (Add a way to set the rubocop binary, the rubocop fallback config, etc.)

**Comment by Naatan** [comment]
Yes please :)

**Comment by Defman21** [comment]
Had to to a rebase for simpler cherry-picking.

**Comment by Naatan** [comment]
Thanks @Defman21 !

**Comment by Defman21** [comment]
This fallbacks on the built-in linter as well as in #2656 (though it works). I guess I should change that too?

**Comment by Naatan** [comment]
Oops, missed that. Yes please, do a new PR for that.

**Pull request merged**
