### PR TITLE
Modules: Notify: description color is now state-foreground; fixed #1494

### LINKED ISSUE #1494: Foreground for state ok, state info, etc. not configurable
### Short Summary
In some themes, the text on notifications is hard to read. The state foreground is configurable, but this doesn't appear to affect the special states.

### Steps to Reproduce
Open Color Scheme Editor. Select **Interface**.

### Expected results
All color combinations for elements should be easy to read.

### Actual results
`state ok`, `state info`, etc. are not easy to read, with `state ok` being next to impossible to understand. Again, if this can be CSSd, I would love to know.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
image
image

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
I'd rather this be explicit vs implicit. Inherit would just create more bugs if the parent CSS changed in the future. So this should actually use state-foreground rather than refer to it.

Did you see if this worked with various color schemes by any chance?

**Comment by Defman21** [comment]
I'll make it explicit and see how it works with different schemes.

**Comment by Defman21** [comment]
@Naatan should the cog and close icon also be stylized using state-foreground color?

**Comment by Naatan** [comment]
No.

**Comment by Naatan** [comment]
Thanks @Defman21 :)

**Comment by Defman21** [comment]
>No.

Yes :P
https://github.com/Defman21/KomodoEdit/blob/8faef6c00076cba0c4cf77afa3804aa0d407ea4d/src/modules/notify/skin/notify.less#L105

**Comment by Naatan** [comment]
Huh, ok then.

**Pull request merged**
