### PR TITLE
Tabstops: respect tabstop id when moving to next tabstop; fixed #2168

### LINKED ISSUE #2168: Respect tabstop number when pressing Tab
### Short Summary

Create this snippet:

```
test1[[%tabstop1:]]
	test0[[%tabstop0:]]
test2[[%tabstop2:]]
```

Press Tab 3 times.

### Expected results

Jump to `test0`, then `test1` and `test2`.

### Actual results

Jump to `test1`, then `test0` and `test2`.

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks @Defman21! :) We'll review this for 10.2.

**Comment by Defman21** [comment]
The mechanism is pretty simple - on each tab press, i'm iterating over current tabstops in asc order and save their start/end positions to a temporary array (within the tabstop object itself), then sort this array which will be iterated again to continue the operation.

**Comment by Defman21** [comment]
btw i think this pr can handle #2169

**Comment by Defman21** [comment]
Looks like this PR is breaking tabstops without a number. Ill investigate more.

**Comment by Naatan** [comment]
> btw i think this pr can handle #2169

How so?

**Comment by Defman21** [comment]
With some magic :P

**Comment by Naatan** [comment]
That does not answer my question in the slightest :p

**Comment by Defman21** [comment]
Im trying to solve some problems right now so I don't know if this pr will solve #2169. Will give an answer soon.

**Comment by Defman21** [comment]
Looks like this PR is not something that Ill able to fix. It requires some serious changes to the whole tabstops functionality and im not gonna take it, sorry :(

**Comment by Naatan** [comment]
No worries, thanks for trying :)

**Pull request closed without merging**
