### PR TITLE
Improved Openfiles Scope Search

### PR DESCRIPTION
**Pull request by ssigwart**
- Splits search into words and checks for words.
- Favors words in the filename.

### CODE REVIEW

**Comment by th3coop** [comment]
I can't actually notice any functional difference between this and master.  I tried the following:
- opened a bunch of files, one has `blah` in the path and one has `blah` in the file name
- access openfiles scope and search `blah`

No matter which branch I'm on, the filename match is always placed at the top of the list.  

The search already works with words as well.  I can see how the change you made should apparently fix the original code NOT supporting words but the original code, somehow, already supports it.

If you have a specific usecase that this is addressing, lay it on me.  So far this PR seems unnecessary (though still really appreciated  :D)

**Comment by ssigwart** [comment]
This is specific to the Open Files scope.  The overall Commando worked well.  Were you testing the right scope?
image

**Comment by th3coop** [comment]
Hrm....I might have been running your branch actually HA.  Since testing some other stuff on another branch and going back to **master** searching by word doesn't work.  So your code works great!  Thanks for your patience @ssigwart.

**Comment by ssigwart** [comment]
@th3coop, No problem.  Thanks for merging in a bunch of my code tonight.

**Pull request merged**
