### PR TITLE
Linter: SCSS: detect rbenv and use it's sh file, otherwise use /path/…

### LINKED ISSUE #1819: SASS Linter does not check syntax if it's installed using rbenv's gem
### Short Summary

`sass` executable which has been installed through rbenv's gem is a bash script and it fails to run.
There's `.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-3.4.22/bin/sass` which is a Ruby script but it's not in PATH variable. I think Komodo should not try to run the executable using `ruby`, because the script contains `#!` declaration. Any shell will handle it properly.

https://github.com/Komodo/KomodoEdit/blob/master/src/lint/koCSSExLinter.py#L118

### PR DESCRIPTION
**Pull request by Defman21**
…to/ruby /path/to/sass command; fixed #1819

Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Defman21** [comment]
Also, an interesting point that `rbenv` is a bash function and not a path to a script, but it still should work :)

**Comment by Defman21** [comment]
Can you put that in 10.1? I'm not able to see SCSS errors in my code because of that :(

**Comment by mitchell-as** [comment]
Too late for 10.1 :( Sorry.

**Comment by Naatan** [comment]
@Defman21 you could work around this by creating an sh file which invokes rbenv and then forwards the call to scss.

Or use NPM's SCSS.

**Comment by Defman21** [comment]
I'll just pass a ruby file. Rbenv has them but there are in some deep location :)

**Comment by mitchell-as** [comment]
Thanks @Defman21 !

**Pull request merged**
