### PR TITLE
Rubocop linter: removed ruby linter fallbacks

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
Did you test that returning nothing doesn't produce errors?

**Comment by Defman21** [comment]
I think returning an empty array would be a better approach so Komodo will think there are no syntax errors. I didn't test the return nothing though.

**Comment by Naatan** [comment]
Please test your changes :)

**Comment by Defman21** [comment]
Well I tested it when there are syntax errors in the code, though I didn't test the failure of the linter 😛

**Comment by Defman21** [comment]
Me and Nathan had a discussion on the irc channel so I'll close that because Komodo isn't able to fallback on the built-in linter if there's another one.

**Pull request closed without merging**
