### PR TITLE
dont show color swatch on less and scss vars, fixes #1920

### LINKED ISSUE #1920: ColorPicker: $<color constant> is a hyperlink
### Short Summary

I think it's related to https://github.com/Komodo/KomodoEdit/issues/1815

With this code:

```scss
.red {
    color: $red;
}
```

Press Ctrl and hover over `$red`. It will be recognized as a hyperlink. You can open color picker and change `red` part to something else, `$` will be there.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Ubuntu 16.04

### PR DESCRIPTION
**Pull request by babobski**
Added a fix for #1920 a simple check if it's not a less or sass/scss var.

### CODE REVIEW

**Comment by Defman21** [comment]
Hmm, I'd rather use `isVar` variable and `&& !isVar` check. It's not important, but as for me it's easier to read :)

**Comment by cgchoffman** [comment]
> Hmm, I'd rather use isVar variable and && !isVar check. It's not important, but as for me it's easier to read :)

If you're worried about ease of reading you should comment on the commit at the line you're referring to.

Having said that,  I agree with @Defman21 except wouldn't it be more clear to name it `isNotCSS`?  It's not clear to me what `var` is supposed to mean in this context.

**Comment by Defman21** [comment]
>If you're worried about ease of reading you should comment on the commit at the line you're referring to.

Ok, thanks for pointing me to the right way :)

**Comment by Naatan** [comment]
I thought I was the nitpicker :p 

Thanks @babobski, I'll try this out and merge at some point today :)

**Comment by Defman21** [comment]
>I thought I was the nitpicker :p 

Haha, you're not the only one now! :P

**Comment by Defman21** [comment]
I've built it and it works fine for me in SCSS. Gives `Not Implemented Error` which means that Komodo recognize it as a hyperlink, not a color.

**Comment by Defman21** [comment]
image

**Comment by Naatan** [comment]
Looks like a good PR overall, the only part I was a bit worried about was the Rx use for something so simple. Did some profiling to see if I was right to be concerned:

```
var text = '@red';
console.time('1');
for (let x = 0; x<1000;x++)
    /[@\$]/.test(text);
console.timeEnd('1');

var text = '@red';
console.time('2');
for (let x = 0; x<1000;x++)
{
    ['@', '$'].indexOf(text.substr(0,1))
}
console.timeEnd('2');

var text = '@red';
var first;
console.time('3');
for (let x = 0; x<1000;x++)
{
    first = text.substr(0,1);
    first == '@' || first == '$';
}
console.timeEnd('3');
```

Results:

```
1: 1.491ms
2: 1.149ms
3: 0.087ms
```

The numbers are pretty negligible overall, I don't think it will make any noticeable difference to the end user. But since the difference between 1 and 3 are so big I'll go ahead and use the version that performs better, cause why not?

There, now give me my nitpicker title back @Defman21.

Will add this in myself when I merge, no action required.

**Comment by Naatan** [comment]
Thanks again @babobski :)

**Comment by Defman21** [comment]
1 sec and 0.08sec is actually a big difference.

**Comment by Naatan** [comment]
Yes it is. But those aren't seconds.

**Comment by cgchoffman** [comment]
> 1.5 sec and 0.08sec is actually a big difference.

I read it the same way as you @Defman21 :D But it's 0.08 ms, aka. 0.00008 seconds.  Great minds think alike.

**Comment by Defman21** [comment]
Oh wait... Haha!

**Pull request merged**
