### PR TITLE
PHP CodeIntel Updates

### PR DESCRIPTION
**Pull request by ssigwart**
- Use FQN for PHP types
- Skip outdated trg-from-pos requests.
  - For large files, trg-from-pos requests can back up as you type. I can't think of any reason why we'd need to process a request if we got a newer request for a new position.
- PSR4 updates
  - Allow filenames like MyClass.class.php
  - When doing PSR4 lookup, only concider paths that match namespace
  - Do not look at global scope with doing PSR4 lookups
- Use scandir for PHP import lookup.

### CODE REVIEW

**Comment by ssigwart** [comment]
It's probably best to look with whitespace ignored:
https://github.com/Komodo/KomodoEdit/pull/3770/files?w=1

**Comment by ssigwart** [comment]
I've been using this patch for the mast month and a half.  It seems to work well.  I also just adding another commit to fix a PSR4 bug:
https://github.com/Komodo/KomodoEdit/pull/3770/commits/bed4d635f8220682ad6c1a0029defe74aefef515?w=1

I think the bug was there before this change too, but I'm not positive.  If a PSR4 lookup was attempted, but failed, it would throw an error causing the whole lookup to fail.  I was seeing this when doing something like this:
```php
$arr = functionThatReturnsAnArrayContainingAClassInANamespace();
foreach ($arr as $row)
	$row-> // Lookup fails here
```

**Comment by ssigwart** [comment]
@th3coop, do you think this can be included before the next production release?  I've been running it locally the past 4 months (by manually patching files in the nightly).  While I can't guarantee that it has no bad side effects, it seems to have been working well.

**Comment by th3coop** [comment]
@ssigwart, looks like there's a conflict with `master`.  Can you merge in master and push?  I'll have a look at the PR.

**Comment by th3coop** [comment]
@ssigwart Are there other PRs I've lagged on that you'd like to see in the next release?

**Comment by ssigwart** [comment]
I rebased this branch with master.

> Are there other PRs I've lagged on that you'd like to see in the next release?

I do have some others.  Here they are in what I think are most to least important:
- Look Up Type Inference on PHP Parent #3781
- Handle Object Member Completion on Array Index #3772 
- Write Dirty res_index To Disk #3774
- Add mysqli Back to PHP 7.0 #3771
- Smarty Completions Update #3779
- Try To Reduce Memory Usage of Breadcrumbs #3776

### Very Low Priority
- Notifications clear option #3674
- Filter option for open files #3673

**Comment by th3coop** [comment]
@ssigwart thanks for the list!

**Pull request merged**
