### PR TITLE
Fixed #1052; added //Region support for PHP

### LINKED ISSUE #1052: Folding code defined by regions
Hi folks,

i had read the Issue #715 and want this for JS and/or PHP, too.

Is there a way to add those functionality to other "languages" then CSS?

Best regards

### PR DESCRIPTION
**Pull request by Defman21**
Fixed #1052

### CODE REVIEW

**Comment by Naatan** [comment]
The terminology here is different than from the CSS, I'd prefer us to be consistent.

That said, I'm personally not a big fan of the terminology used for CSS. Is there already a standard for manual code folding patterns like this that's used in other editors?

**Comment by hirnwunde** [comment]
In Visual Studio 2012 i had folded with 
```vb
'region FooBar
    Private Sub SetTextPos(ByVal [text] As String)
        If Me.tb_ActPosX.InvokeRequired Or Me.tb_ActPosY.InvokeRequired Then
            '[ ... ]
        End If
    End Sub
'end region
```
[https://msdn.microsoft.com/en-US/library/9a1ybwek%28v=vs.80%29.aspx](url)

Same behavior in PHPStorm
[https://www.jetbrains.com/phpstorm/help/folding-custom-regions-with-line-comments.html](url)

**Comment by Defman21** [comment]
Fixing your urls:
[MSDN](https://msdn.microsoft.com/en-US/library/9a1ybwek%28v=vs.80%29.aspx)
[PHPStorm](https://www.jetbrains.com/phpstorm/help/folding-custom-regions-with-line-comments.html)

**Comment by Naatan** [comment]
It seems that is the terminology used in the css lexer too. @Defman21 can you change it to that same terminology?

**Comment by Naatan** [comment]
btw I feel for PHP it would be better to do:

```/*region My Reagon name */
foo();
/*endregion*/```

Though I guess there is no harm in supporting both, ie.

```//region My Reagon name
foo();
//endregion```

Note there is no whitespace between the comment prefix and the comment text, I think this makes sense. It prevents false positives.

**Comment by Defman21** [comment]
So.. `#region` for COMMENTBLOCK and `/*region*/` for COMMENT?

**Comment by hirnwunde** [comment]
@Defman21 
Did you see chances to add similar definitions to JavaScript resp. 'src/udl/udl/ecmascript_262.udl'?

**Comment by Defman21** [comment]
Yes, I can add it to JS as well, but first I need the answer from Nathan.

**Comment by hirnwunde** [comment]
for sure :)

**Comment by Defman21** [comment]
Ahh seems like I got it, I didn't know PHP supports `/*comments*/`

**Comment by Defman21** [comment]
@Naatan `/*region My Reagon name */ foo(); /*endregion*/` is not possible due to `fold` does not support regex, so it would be `/*region*/ foo(); /*endregion*/`

**Comment by hirnwunde** [comment]
but you can set a comment one line above the region-comment to add a description for the block like
```php
// My Foo-Region
/*region*/
function foo() {} 
/*endregion*/
```

**Comment by Defman21** [comment]
Yes you can, it's not something that Komodo will catch as a part of a region though.

**Comment by hirnwunde** [comment]
I'm to goofy to compile KomodoEdit for my self.
Did I have to wait if Komodo will release a new version or is there a way to get the win32-binaries containing these changes earlier?
Maybe some nightly-builds or so.

**Comment by Defman21** [comment]
I think that the first nightly build will contain this PR (of course if this is gonna be merged)

**Comment by Naatan** [comment]
@mitchell-as can you confirm? https://github.com/Komodo/KomodoEdit/pull/1057#issuecomment-180068953

**Comment by hirnwunde** [comment]
is [http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/](this) place the right one for the nightly builds?
Because the newest build there (16459) is older then the last release (16460)

**Comment by Defman21** [comment]
```
fold /\/\*(?:region)\*\// SSL_COMMENTBLOCK +
fold /\/\*(?:endregion)\*\// SSL_COMMENTBLOCK -
```

```
statements HT_FOLD . LexToken(LB_REGEX,'/\\/\\*(?:region)\\*\\//',599)
Syntax error at or near line 599, token '/\/\*(?:region)\*\//'
statements HT_FOLD . error
statements . error
. error
empty . LexToken(LB_NAME,'SSL_COMMENTBLOCK',599)
empty . error
. error
. LexToken(PLUS,'+',599)
statements HT_FOLD . LexToken(LB_REGEX,'/\\/\\*(?:endregion)\\*\\//',600)
statements HT_FOLD . error
statements . error
. error
empty . LexToken(LB_NAME,'SSL_COMMENTBLOCK',600)
empty . error
. error
. LexToken(MINUS,'-',600)
luddite: error: LudditeError: could not parse 'udl/php-mainlex.udl': 1 error(s)
cons.pl: *** [build/release/udl/build/PHP/install.rdf] Error 1
cons.pl: errors constructing build/release/udl/build/PHP/install.rdf
```

**Comment by Defman21** [comment]
@hirnwunde yes. There's no new nightly build by now, that's why it has lower build value than the release.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoEdit/pull/1057#issuecomment-180075912

That doesn't mean it's not possible or there isn't a way. In this case we don't even need regex, we just need to check if a line starts with `//region`

**Comment by Defman21** [comment]
I'll try.

**Comment by mitchell-as** [comment]
@Naatan the "fold" keyword does not support regex, just strings as @Defman21  said.

**Comment by Naatan** [comment]
@mitchell-as the question is whether there is a way to fold `//region RANDOM TEXT`. With regex or otherwise.

**Comment by Defman21** [comment]
```
<?php

/*region MyRegion*/

function hi() {
    
}

/*endregion*/

hi();
```

**Comment by Naatan** [comment]
That's great @Defman21, I'll test when I have a chance :) Note though that you have the same rule twice in there. You need to remove one.

**Comment by Defman21** [comment]
IIRC if I remove SSL_COMMENT then SSL_COMMENTBLOCK won't work. Take a look at https://github.com/Defman21/KomodoEdit/blob/issue-1052/src/udl/udl/phplex.udl#L600-L604

**Comment by Naatan** [comment]
Ahh I missed that, nvm then :)

**Comment by Naatan** [comment]
Thanks @Defman21 :)

**Pull request merged**
