### PR TITLE
Console: don't save empty strings to history so it won't break; fixed…

### PR DESCRIPTION
**Pull request by Defman21**
… #2458

Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
Nice @Defman21 !

2 minor things

 1. you seem to have messed the indentation, looks like an extra space?
 2. instead of regex you can just use `.trim()` - this one doesnt really matter but fyi.

**Comment by Defman21** [comment]
Don.

**Comment by Defman21** [comment]
wait.

**Comment by matkoniecz** [comment]
@Naatan It seems that now this PR is ready.

**Comment by Naatan** [comment]
@matkoniecz no worries, it's scheduled for 11. I'll get to it :)

**Comment by Naatan** [comment]
Thanks @Defman21 !

**Pull request merged**
