### PR TITLE
Colorpicker: removed ability to resize the dialog (the colorpicker is…

### PR DESCRIPTION
**Pull request by Defman21**
… not responsive-design)

Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks @Defman21! Unfortunately though this isn't the proper way of limiting window size. The proper way would be to disable window resizing (resize=false) in the openDialog call.

**Comment by Defman21** [comment]
Would you mind re-opening this if I'll do that?

**Comment by Naatan** [comment]
Ahh I think the custom window decorations don't work with resize=false. I'll have to look into that. I suppose as an interim solution your CSS tweak would work. I cannot reopen this though, as it says your branch has changed.

**Comment by Defman21** [comment]
Yeah. ammending last commit was a bad idea...

**Pull request closed without merging**
