### PR TITLE
Colorpicker: added RGBA support

### PR DESCRIPTION
**Pull request by Defman21**
This commit will add a new input where you can control the opacity of the color. It can convert hex, rgb and hls color to rgba (I don't know how this is working, looks like Komodo is handling it somewhere else, not inside the colorpicker).

If the opacity is 1, rgba will be transformed to rgb.

The preview also will use the opacity color.

Todo:

* [x] Make previous color preview also use transparency 

colorpicker

### CODE REVIEW

**Comment by Defman21** [comment]
@Naatan also, do you have any ideas how I can make this input better?

**Comment by Naatan** [comment]
Hi @Defman21, great work so far! Could you please make it use the actual rgba value and not add a new input field?

ie. 
image

**Comment by Defman21** [comment]
Hmm, good idea. I'll try do something like that.

**Comment by Defman21** [comment]
upd

**Comment by Naatan** [comment]
Much better. Unfortunately you seem to have grouped in a refactoring of JS formatting in your PR. This is a big nono, can you please revert that?

**Comment by Defman21** [comment]
I'd try to "tabify" everything again.

**Comment by Defman21** [comment]
That didn't help.

**Comment by Defman21** [comment]
FFS I DID IT YEAH

**Comment by Naatan** [comment]
Hate to be difficult here, but I still see a ton of meaningless whitespace and semicolon changes that should not be part of this PR.

Also please be sure to squash your changes once you are done.

Not to sound like I don't appreciate your efforts here, I certainly do. But especially for PR's we have to make sure that the commits are clean and to the point.

**Comment by Defman21** [comment]
I'll restore each tab manually.

**Comment by Naatan** [comment]
It's not just tabs though. Please check the "Files changed" tab on github and see all the changes that are not relevant to this commit (ie. changes that do not contribute to "adding rgba support").

**Comment by Naatan** [comment]
I think if you `git revert --soft` you should be able to cherry pick your changes.

**Comment by Defman21** [comment]
I'll send you a new PR. It would be much easier to just copy my changes without touching EOL and the rest.

**Pull request closed without merging**
