### PR TITLE
Only Cache Last 2 Buffers

### LINKED ISSUE #3769: Buffers are cached forever in driver.py
### Summary
https://github.com/Komodo/KomodoEdit/blob/99b37b1c7eef04d6a918b7f3f1db74adf19c80a6/src/codeintel/lib/codeintel2/oop/driver.py#L337
Whenever `get_buffer` is called, it stores the buffer in `self.buffers[path]`.  However, it never seems to clean up the cached buffers.  I wonder if this is the reason Komodo gets slow after a few hours of usage.

## Possible Updates
My initial thought is to clear the cache when a file is closed.  I'm not sure how to get that information to the driver class though.

### Platform Information

Komodo Edit
GitHub master

### PR DESCRIPTION
**Pull request by ssigwart**
- Closes #3769

### CODE REVIEW

**Comment by th3coop** [comment]
@ssigwart 2 is too few.  Buffers are capped at 1 MB. Why don't you use:
```python
from collections import deque

self.buffers = deque([None]*20, 20)
...
self.bugger.appendleft(newbuffer)
```

Then you don't have to manage moving things around and we'll always have a cache of 20 buffers that will never be bigger than 20MB.

**Comment by ssigwart** [comment]
Why do we need so many?  It seemed like `get_buffer` is only called for the current file you are on.  I figured I'd keep the last one too in case you're flipping back and forth between two files (or are in split view).

With `deque`:
1.  I was looking to see if there was a standard priority dictionary, but couldn't find one.  Wouldn't `deque` mean I'd need to reorder it whenever a new `get_buffer` call comes in (and it's not first on the list).  Would that and having to do the lookup through 20 items be a performance problem.
2.  Is this 1MB limit where the 20MB total comes from?
https://github.com/Komodo/KomodoEdit/blob/f4c38968d7e00cda97ad531a87b7e2a1b57b9e07/src/codeintel/lib/codeintel2/manager.py#L421

**Comment by th3coop** [comment]
> Why do we need so many? It seemed like `get_buffer` is only called for the current file you are on.

I'm basing this on the fact that the original writer left it so open and assuming it wasn't an over site.  Based on that I'm assuming that loading a buffer cause a ton of work to start and if that's the case, I know in a not very rare session for myself that would mean having at least 10 files open and that buffer triggering all the time as I flipped between files.

RE Deque:  Ya deque won't work.  Silly me, we need a dict.  What about [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict)?  They provide an example of a least recently used implementation even.

Yes, that's where I was getting the buffer size references from.

**Comment by ssigwart** [comment]
Ok.  I don't like when I come across a git blame the is the first commit.  I can't tell what the author's intent was.

Thanks for the OrderedDict tip.  The example was for Python 3, but I ported it to Python 2.  If you want me to squash the commits, let me know.

**Pull request merged**
