### PR TITLE
Try To Reduce Memory Usage of Breadcrumbs

### LINKED ISSUE #3775: Investigating possible memory leak in breadcrumbs
See https://community.komodoide.com/t/whats-the-expected-max-memory-usage/4710/2

### PR DESCRIPTION
**Pull request by ssigwart**
- Closes #3775
- Use event delegation instead of individual event handlers.
- Make sure to remove event listeners on close.
- Unset variables on close (not sure if it helps prevent memory leaks or not.

I still see a line for breadcrumbs in memory usage after closing all files, but at least it seems a little smaller than before.

### CODE REVIEW

**Comment by th3coop** [comment]
I'm reluctant to merge this one if you're not seeing much of a change.  The memory usage of your breadcrumbs hasn't changed with this update?

If the bug lies within Mozilla then we'll have to find a patch and back port it which can be more pain than it's worth.

**Comment by ssigwart** [comment]
For the breadcrumbs, I've been using it locally and haven't seem as high of memory usage.  In my testing, I was definitely seeing less memory being used in general.  I was never able to get the memory quite as high as I was seeing in real usage in testing, so I can't be sure it won't get as big, but it seems to help.

The memory used when all tabs are closed is possibly still and issue.  As I mentioned in the forum, a lot of other panels have memory leaks when you close them (“About”, “Run”, etc.).  I feel like that's probably a Mozilla issue.  Should I open an issue about them?  I couldn't find anything in Mozilla that might fix that, but maybe you or someone else would have better luck.

**Comment by th3coop** [comment]
@ssigwart have you been running this patch since you submitted it?

**Comment by ssigwart** [comment]
@th3coop, I can't remember.  I think I was, but when I went to the new nightly last week, I think it overwrote it.

**Comment by th3coop** [comment]
Ok, i've merged a couple PHP code intel tickets and will push a nightly with those.  I'll merge this one next week just to space things out.

**Comment by ssigwart** [comment]
Great.  Thanks.

**Comment by th3coop** [comment]
Nvm.  That nightly didn't make before the noon cut off.  I'll just build another one and push by end of day so it's published tomorrow

**Comment by ssigwart** [comment]
@th3coop, it doesn't look like this ever got merged into master.  Can you do that?  I recently went from my custom build of 11 to 12 and it seems laggy again.  I'm wondering if this might be the reason.

**Comment by th3coop** [comment]
Bit late now but yes.  Looks like I merged it into 11.1.x.  Just merged it into master and pushed it.

**Comment by ssigwart** [comment]
Thanks!

**Pull request merged**
