### PR TITLE
Startup Wizard: changed IDE to Edit

### LINKED ISSUE #2572: First Start Wizard says Komodo IDE instead of Komodo Edit
### Short Summary

If you run Komodo Edit for first time (or run the wizard again), you'll see Komodo IDE in the title of the window.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* master branch
*Operating System (and version)?* Arch Linux 

### Additional Information

screenshot_20170503_135401

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

Fixed #2572

### CODE REVIEW

**Comment by cgchoffman** [comment]
I must have missed your pull request @Defman21.  i implemented this fix already.  Doesn't seem to have worked I guess.

**Comment by Naatan** [comment]
Reopening as it appears Carey's commit did not land on master.

**Comment by cgchoffman** [comment]
Sure it did.  And why would we need a pull request?  Just Cherry-pick if it wasn't. https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/startupWizard/startupWizard.xul#L19

**Comment by cgchoffman** [comment]
See my comments in your ticket @Naatan: https://github.com/Komodo/KomodoEdit/issues/3397#issuecomment-349054657

**Comment by Naatan** [comment]
@cgchoffman could you test on OSX? That's where it was reported to me.

**Comment by cgchoffman** [comment]
Can't reproduce on OSX either.

**Pull request closed without merging**
