### PR TITLE
Find Case Sensitivity Fix, Current Tab CSS, & Minor Fixes

### LINKED ISSUE #3655: Variable Highlighting Resets Find Case Sensitivity
The following line causes preferences to be set to case sensitive.  This causes Find to be set to case sensitive on the next reboot.
https://github.com/Komodo/KomodoEdit/blob/71694f78e2fe602d30a7ee6cd7e5a67d5ed159cb/src/chrome/komodo/content/codeintel/codeintel.p.js#L1348

### PR DESCRIPTION
**Pull request by ssigwart**
- Fix #3655 
- Add CSS for current tab
image
- Fix open files variable name
- Other javascript warning handling

### CODE REVIEW

**Comment by cgchoffman** [comment]
Did not see this PR.  My notifications have been broken for a while now.

**Comment by ssigwart** [comment]
@th3coop, do you think you can look at this pull request for the next nightly?

**Comment by th3coop** [comment]
@ssigwart, sorry about that.  It's sprint end right now.  I'll squeeze this in today if I can.  Sorry for once again forgetting about it.

**Comment by ssigwart** [comment]
Thanks, @th3coop!  That case sensitivity reset has been bugging me for years.  Thanks for getting all my bug fixes merged in.  I think the remaining pull requests are all just nice to have improvements, so not high priority.

**Comment by th3coop** [comment]
@ssigwart forgot to push a nightly.  Doing that now.  If you're already on a nightly you'll get prompted to update at some point after noon PST.  I'll be hitting the PR backlog when in my downtime!  Thanks for your activity!

**Comment by ssigwart** [comment]
Thanks, @th3coop!

**Pull request merged**
