### PR TITLE
Make changes to support both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__futurize --stage1 -w .__  # http://python-future.org

### CODE REVIEW

**Comment by th3coop** [comment]
Thanks @cclauss.  Was this all done using a script?

**Comment by cclauss** [comment]
This PR was created with Python future as was written in the commit message.

**Comment by th3coop** [comment]
@cclauss, this would likely break a lot of things in Komodo.  Making the code Py3 compatible is one of a many steps we'd have to make in order to get this working.  I'm going to have to pass on this PR but your effort and interest is appreciated.

**Comment by cclauss** [comment]
Stage1 are “safe” changes the work with both Py2 and Py3.

**Pull request closed without merging**
