### PR TITLE
Fixed #60

### LINKED ISSUE #60: Do not open/close a folder by right click with Expand on click enabled
I don't want to open or close a folder in Places if I click right mouse button on it. It should save the state.

### PR DESCRIPTION
**Pull request by Defman21**
Fixed #60

### CODE REVIEW

**Comment by Naatan** [comment]
I'm not sure which keycode "3" is (should be in a comment), but it seems to now just disable click to expand altogether.

**Comment by Defman21** [comment]
>I'm not sure which keycode "3"

Right Mouse Button.

**Comment by Naatan** [comment]
Looking at the API it seems event.which is not standardized (yet), the better option would be: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

I'll see if I can get it to work for me. Event.which just makes it not work at all, regardless of the button pressed.

**Comment by Defman21** [comment]
It works fine for me.. hmm.

**Comment by Naatan** [comment]
Hmm seems something else was going on, I got it working now.

Would you mind using the following:

```
if (this.view.isContainer(index) && ko.prefs.getBoolean('pref_places_singleClickExpand', false) && event.buttons === 1) {
```

so `event.buttons === 1` instead of `event.which` or `event.button`, as this will account for both left handed mouse users as well as the use-case where multiple mouse buttons were pressed.

Thanks :)

**Comment by Defman21** [comment]
Yeah no worries :)

**Comment by Defman21** [comment]
@Naatan I think we should prevent expanding if a modifier key (Shift/Alt/Ctrl) is pressed. What do you think?

**Comment by Naatan** [comment]
Yes, that makes sense.

**Comment by Defman21** [comment]
I think I don't have to create a variable for it.

**Comment by Defman21** [comment]
Merged everything into one commit.

**Comment by Naatan** [comment]
Thanks @Defman21 :)

**Pull request merged**
