### PR TITLE
Misc: fixed View Log File not working in Safe Mode (fallback on <ver>…

### LINKED ISSUE #1947: View log file does not work in safe mode
### Short Summary

It tries to open `~/.komodoide/10.1/pystderr.log` instead of `~/.komodoide/10.1-kotemp-original/pystderr.log`

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 beta
*Operating System (and version)?* Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Defman21**
…-kotemp-original before throwing an exception); fixed #1947

Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks @Defman21 ! Unfortunately I don't agree with this one. It is opening the log file for a past instance of Komodo. The fix should actually open the log file for the current running instance.

**Comment by Defman21** [comment]
It's opening `~/.komodoide/10.1-kotemp-original`, which I thought is referring to current temporary instance of Komodo. This is not true?

**Comment by Naatan** [comment]
No that refers to the actual profile directory which was moved aside.

**Comment by Defman21** [comment]
I've found that Komodo still appends to `10.1-kotemp-original/pystderr.log` when you restart in Safe Mode. So I assume it would require much more changes rather than pointing safe-mode'ed Komodo to that file.

**Pull request closed without merging**
