### PR TITLE
PHP Array Fixes

### PR DESCRIPTION
**Pull request by ssigwart**
See description in #3741

### CODE REVIEW

**Comment by ssigwart** [comment]
I found some other things that resulted in no type being returned.  I figured it would be better to at least default to the first type.  I added a new commit, so this branch should now handle all of this:
```php
/**
 * @param Test $test Test
 * @param Test2|null $a Test
 * @param (Test|null)[] $possiblyNulls Variables
 * @param ((Test3|Test2|(Test1|Test4)[])|null)[] $outOfControl Variables
 * @param Test[] $vars Variables
 * @param Test[][] $vars2 Variables
 * @param Test[][][] $vars3 Variables
 *
 * @return Test|null
 */
```

**Comment by ssigwart** [comment]
I realized that references weren't handled and `@property*` and `@method` needed the same complex type handling.  So now all of these should work:
```php
/**
 *
 * @property Test2 $normal
 * @property Test2|null $something
 * @property-read Test2|null $somethingRo
 * @property-write (Test2|null)[] $somethingRw
 *
 * @method Test2 getTest2A()
 * @method Test2|null getTest2B()
 * @method (Test2|null)[] getTest2C()
 */
class Test
{}

/**
 * Function
 *
 * @param int &$i
 */
function func(&$i)
{}
```

I think I'm done now.  This is ready for review.

**Comment by ssigwart** [comment]
Ok.  I think this is really the last one.  I updated it to handle this:
```php
function func()
{
	/** @var (Test|null)[] */
	$maybeVars = null;
}
```

**Comment by th3coop** [comment]
This isn't working for any examples that have `|null`.  I don't know PHP enough to know what should be going on but using the this comment for example, https://github.com/Komodo/KomodoEdit/pull/3742#issuecomment-482743074
```php
/**
 *
 * @property Test2 $normal
 * @property Test2|null $something
 * @property-read Test2|null $somethingRo
 * @property-write (Test2|null)[] $somethingRw
 *
 * @method Test2 getTest2A()
 * @method Test2|null getTest2B()
 * @method (Test2|null)[] getTest2C()
 */
class Teststuff
{}
```

When I do ` Teststuff->` I only get completions for `normal`, `getTest2A` and `Test2` ( I don't think that last one should even happen).  When I remove all `|null` parts i get all completion suggestions.

So,
```php
/**
 *
 * @property Test2 $normal
 * @property Test2 $something
 * @property-read Test2$somethingRo
 * @property-write Test2[] $somethingRw
 *
 * @method Test2 getTest2A()
 * @method Test2 getTest2B()
 * @method Test2)[] getTest2C()
 */
class Teststuff
{}
```

**Comment by th3coop** [comment]
Sorry for the delay, vacation called!

**Comment by ssigwart** [comment]
That's weird.  It works for me (though I don't think it did with `bk build quick`).  Do you have a `Test2` class defined?

Hope you enjoyed the vacation.

**Comment by th3coop** [comment]
If it worked for you then I'm confident that it's my lack of PHP mojo that was getting in the way.  I did have a `Test2` class defined.

**Pull request merged**
