### PR TITLE
ColorPicker: added RGBA support

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by Naatan** [comment]
Seems to work alright except for one issue I've found so far: When opening it from an RGB() color it shows an RGBA value. That in itself is not necessarily bad, but editing the value completely breaks the color picker.

I think it makes sense for it to always show RGBA() instead of RGB(), but it should respect the input value that was used, unless the alpha is changed.

**Comment by Defman21** [comment]
Works fine for me.
I clicked on `rgb(25, 25, 25)` and tried to change it using the color map. Works fine. Tried to change it using the corresponding input and it still works fine. Anything in your error logs after color picker has been broken?

**Comment by Defman21** [comment]
Ah, I reproduced another bug when you set r, g or b more than 255.

**Comment by Naatan** [comment]
Try changing the input field without having first changed it using the color map. I can reproduce the issue consistently.

**Comment by Defman21** [comment]
I assume the rgb field?

**Comment by Naatan** [comment]
Yes

**Comment by Defman21** [comment]
I've pushed a fix which should solve the issue. At least I'm not able to reproduce it anymore.

**Comment by Naatan** [comment]
Perfect, looking good now! :)

**Comment by Naatan** [comment]
Thanks Defman :) Great work.

**Comment by Defman21** [comment]
Thanks. I wanted to merge my latest commit into first, but seems like you're ok with my meaningless messages in them 😛

**Comment by Naatan** [comment]
It's just one commit, all good.

**Pull request merged**
