### PR TITLE
Utils: Docklet: fixed docklet run failing with 'Couldn't load XPCOM' …

### LINKED ISSUE #2510: Unable to run Komodo using docklet run
### Short Summary

title.

### Steps to Reproduce

`./util/docker/docklet run`

### Expected results

Komodo runs.

### Actual results

```
XPCOMGlueLoad error for file /home/defman/projects/komodo/source/mozilla/build/moz3500-ko10.10/mozilla/ko-rel/dist/bin/libnssutil3.so:
/home/defman/projects/komodo/source/mozilla/build/moz3500-ko10.10/mozilla/ko-rel/dist/bin/libnssutil3.so: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

### Platform Information

*Komodo Edit or IDE?* Edit, master branch
*Komodo Version?* 10.10-devel
*Operating System (and version)?* elementary OS 0.4

### Additional Information

manually ssh'ing in the container (`docklet ssh`) and running `bk run` works fine.

### PR DESCRIPTION
**Pull request by Defman21**
…error; fixed #2510

Signed-off-by: Defman21 <i@defman.me>

### CODE REVIEW

**Comment by Naatan** [comment]
This would run it over SSH, which is not what I want it to do.

**Comment by Naatan** [comment]
This would make it run via SSH, which is not what I want it to do.

**Comment by Defman21** [comment]
I'm not sure you'll be able to run it outside of the ssh connection because the building process makes some symlinks and they work only in the container.

**Comment by Naatan** [comment]
Oh you sure can, cause that's what I do :) You just have to make sure that you have local paths that match the paths used on the docker image.

**Comment by Defman21** [comment]
Well that's ruins the idea of docker imo (no harm (yeah symlinks aren't harmful but whatever) for your system) but okay, I'll patch that file locally then.

**Comment by Naatan** [comment]
The idea of docker is to build Komodo in a pristine environment, not RUN it in one. It's no different than having a build server build Komodo, except now the build server is docket.

**Comment by Defman21** [comment]
Still the issue is there and it has to be fixed somehow. I hope you have an idea how to do that w/out symlinking the libs locally. (or at least do that automatically).

**Comment by Naatan** [comment]
You only have to symlink one directory, the one that Komodo is under on the docker image. Or if you image and package the build then you don't need to worry about this at all.

**Pull request closed without merging**
