### PR TITLE
Fixed #203

### LINKED ISSUE #203: Improve Doc popups for functions
You all guys know about PHPDoc and JSDoc but the popups which generated by depending on the PHPDoc/JSDoc comment looks ugly now:
```php
/**
 * The best function you ever see
 * @param	Boolean	$arg1	True or false, if true - you will die, if false - you will die faster
 * @param	Number	$arg2	How long you want to live (in year)
 * @param	String	$arg3	Your name
 * @return	Boolean			Will you die or not
 */
function my_func($arg1 = true, $arg2 = 123, $arg3) {
  
}
```

```text
The best function you ever see
@param Boolean $arg1 True or false... bla-bla-bla
```

I sure it should looks like that:
```text
The best function you ever see
<Boolean>$arg1 - True or false... bla-bla-bla
```

### PR DESCRIPTION
**Pull request by Defman21**
I sure as hell my changes requires some refactoring but my English not that good to call variables better than now.

### CODE REVIEW

**Comment by Defman21** [comment]
```php
<?php

/**
 * Do something
 * @param Boolean $arg1 If true - do some stuff
 * @param Boolean $arg2
 * @return Boolean
 * Another docs
 * @since 1.0
 * @author John Smith jsmith@pod1.mars
 * @see http://google.com/
 */
function test($arg1 = true, $arg2 = false) {
  return true;
}

test(|); // | - cursor
```
The tooltip will be
```
boolean test(Boolean $arg1 = true, Boolean $arg2 = false)
Do something
<boolean>$arg1 If True - do some stuff
<boolean>$arg2
Returns boolean
Another docs
Since 1.0
Author John Smith jsmith@pod1.mars
See http://google.com/
```

**Comment by Naatan** [comment]
Nice work Defman! I'll try to review next week and merge it in if all is good.

**Comment by Naatan** [comment]
Integrated! Thanks Defman :) Made some minor alterations here - https://github.com/Komodo/KomodoEdit/commit/b832360e37fe1de445aa0a5738b9fea5b55cb030

**Comment by Defman21** [comment]
Thank you for your fixes :)

**Pull request merged**
