### PR TITLE
Smarty Completions

### PR DESCRIPTION
**Pull request by ssigwart**
- Based on Twig code.

### CODE REVIEW

**Comment by ssigwart** [comment]
I added a few more standard completions and added variable completions.  It's not perfect because it would need to look up `$tpl->assign(...)` from the PHP that includes the template or from parent templates that call {include file="..."}, but that's infeasible.  Instead, it just searches the current .tpl file to find any variable you've previously used or assigned.

**Comment by th3coop** [comment]
@ssigwart is that regex used elsewhere?  Is there another op for optimization?  Taking this for a spin now.

**Comment by th3coop** [comment]
I can't seem to get modifiers and var_keys to trigger.  I'm probably doing something wrong but could you provide an example of where those two groups should trigger?  Not for every item in those lists, just a general example of where they should trigger.

**Comment by ssigwart** [comment]
I don't think the regex is used elsewhere.  It was one I wrote.

Here's how you trigger these:
```smarty
{* Trigger smarty_tags *}
{
```

```smarty
{* Trigger smarty_var_keys *}
{$smarty.
```

```smarty
{* Trigger smarty_default_modifier_names *}
{$variable|
```

```smarty
{* Trigger variable completions *}
{assign name="myVar" value=1}
{$

```

**Comment by th3coop** [comment]
> I don't think the regex is used elsewhere. It was one I wrote.

Thanks for clarifying!  And thanks for the examples.

**Pull request merged**
