### PR TITLE
Apply ccache patch

### PR DESCRIPTION
**Pull request by ssigwart**
- Applying patch from https://bugzilla.mozilla.org/show_bug.cgi?id=1105090

### CODE REVIEW

**Comment by cgchoffman** [comment]
@ssigwart could you elaborate on this?  What issue did you hit that this resolves?  It looks like it effects builds which we're currently not having any issues on Windows (or any other platform we build on).

**Comment by ssigwart** [comment]
It was the "Failed to parse ccache stats output: primary config" error from https://community.komodoide.com/t/failing-to-build-mozilla-from-trunk/2087/2.  I have version 3.6, but I really don't know if this helped or not.  However, it seemed like it's the same code in the `else` part, so it probably wouldn't break anything.  I struggled getting Mozilla to build the first time taking a few days of trying, but wrote up instructions.  Then I had to rebuild using the instructions and it worked fine with a few minor things I probably just forgot to put in the instructions.  Then I tried to rebuild after the dropdown patch and it keep failing.  I'm not really sure why since I was using the same instructions.  Then I tried this patch and it worked, but honestly it could just be coincidence.  I'd be fine with not merging it for now.

**Comment by cgchoffman** [comment]
Thanks for clarifying.  Since the README says to use ccache 3.1 as it will break otherwise.  The follow out from this change isn't worth the benefit of the update.  I'm going to pass on it, sorry to make this work for nothing.

**Comment by ssigwart** [comment]
No problem.  I'll just keep it around in my fork for when I need to rebuild mozilla.

**Pull request closed without merging**
