### PR TITLE
Fixed #2519

### LINKED ISSUE #2519: Options 'Copy' or 'Move' are not working in Commando
### Short Summary

Options 'Copy' or 'Move' are not working in Commando. Even if it does something in the background there are no notifications.

### Steps to Reproduce

1. Search for files in Commando
2. Select any file
3. Use right arrow key to display file options
4. Select copy or move

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2 RC2
*Operating System (and version)?* macOS

### Additional Information
image

### PR DESCRIPTION
**Pull request by Defman21**
Fixed #2519

### CODE REVIEW

**Comment by Naatan** [comment]
This doesn't appear to have a reset, so it would always stay on that message?

**Comment by Defman21** [comment]
Nope, when the user pastes a file, it resets. (calling pinTipMessage with `null` or `false` argument resets the tip)

**Comment by th3coop** [comment]
@Defman21 sorry for the long wait.  This seems to work great.  Could you resolve the conflicts and I'll get it merged in.

**Comment by Defman21** [comment]
Done

**Pull request merged**
