### PR TITLE
New Laravel Blade directives

### PR DESCRIPTION
**Pull request by lagbox**
New Blade directives:

```php
@extends(...)

@push (...)
@endpush

@stack(...)

@inject(...)

@each(...)

@continue / @continue(...)
@break / @break(...)

@hasSection(...)

@can(...)
@endcan
```

**Checklist:**
- [x] Add new directives
- [x] Test the new directives added.

#1395 

Future PR to add the new echos for blade.
```php
// unescaped echo
{!! ... !!}
// bypass parsing of echo, leaves behind {{ ... }}
@{{ ... }}
```

### CODE REVIEW

**Comment by Defman21** [comment]
>I need to test these, I suppose by recompiling the UDL stuff.

Yep. You'd need to re-compile UDL. However, just re-build Komodo itself (`bk build`).

**Comment by Naatan** [comment]
@mitchell-as I'll leave it to you to merge this (or not) - but don't merge it until after we branch for 9.0.1

**Comment by Defman21** [comment]
9.0.1?

**Comment by Naatan** [comment]
Oh you're right, should be 9.1.

**Comment by Defman21** [comment]
lol

**Comment by lagbox** [comment]
I removed the new Blade Echos from this PR and limited this to only adding missing directives.

**Comment by mitchell-as** [comment]
Thanks!

**Pull request merged**
