### PR TITLE
Remove Unsupported Edit Scheme Data

### LINKED ISSUE #3735: IDE Collab Schemes Cause Edit Error Log Messages
### Short Summary
Each new tab results in color scheme errors in `pystderr.log`

### Steps to Reproduce
Open a new tab in Komodo Edit

### Expected results
Nothing in `pystderr.log`

### Actual results
This in `pystderr.log`:
```
[2019-04-10 20:48:21,509] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2019-04-10 20:48:21,509] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2019-04-10 20:48:21,509] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2019-04-10 20:48:21,509] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2019-04-10 20:48:21,510] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2019-04-10 20:48:21,510] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2019-04-10 20:48:21,510] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2019-04-10 20:48:21,510] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
```

### Platform Information
Komodo Edit 11.1.2 Nightly
maxOS Mojave

### Additional Information
@th3coop, this is just a minor annoyance that I'd like to get rid of.  I can think of 3 options, which would be less obtrusive to your work on IDE?
1.  Add the offending indicators in the following with a new `DECORATOR_NO_DISPLAY` constant.
https://github.com/Komodo/KomodoEdit/blob/8978a84307a3390c1363cff91bc505dd7c461d81/src/schemes/styles.py#L581-L589
2.  Update the following to skip the warning on those indicators:
https://github.com/Komodo/KomodoEdit/blob/8978a84307a3390c1363cff91bc505dd7c461d81/src/schemes/koScintillaSchemeService.p.py#L978
3.  Update all the color schemes to remove the indicators.

### PR DESCRIPTION
**Pull request by ssigwart**
- Closes #3735

### CODE REVIEW

**Comment by th3coop** [comment]
Exactly what i was thinking.  @Naatan this is to remove a bunch of warnings in the logs for these indicators that shouldn't be in Edit.  Does this raise any alarms for you?  Context: https://github.com/Komodo/KomodoEdit/issues/3735#issuecomment-481945214 

Sorry @ssigwart, I should have done this before you submitted a PR but i honestly thought i had more time before you went at it!  It's likely fine.

**Comment by Naatan** [comment]
How did you conclude that those properties are unused? It doesn't seem like they would be unused, but it's been a long time, I cannot recall what happened there.

**Comment by ssigwart** [comment]
They generate errors in the error log.  I checked for and removed all uses in the repo.  They didn't seem to be used.  Also, they seemed to be IDE specific features.

**Comment by Naatan** [comment]
Ahhh that's the key! These are IDE only. So @th3coop make sure you DON'T merge this into IDE.

Thanks @ssigwart !

**Comment by th3coop** [comment]
@Naatan, that would be an ironic merge haha.  I won't merge it into IDE, I promise!

**Pull request merged**
