### PR TITLE
Docker: Use Ubuntu 14.04 image, a lot of dependencies were removed from 12.04

### PR DESCRIPTION
**Pull request by Defman21**
I've tested it before creating a pull request. Everything works fine :)

### CODE REVIEW

**Comment by Naatan** [comment]
I'll have a look at merging this once I have some time to test it, but this is great, thanks @Defman21 :)

One thing I'd want to do if we merge this though is actually remove the dependencies.

**Comment by Defman21** [comment]
>One thing I'd want to do if we merge this though is actually remove the dependencies.

How? Distributing an image with already installed dependencies?

**Comment by Naatan** [comment]
I thought by dependencies you were referring to our dependencies, not Ubuntu's dependencies.

**Comment by Naatan** [comment]
I'm gonna close this on the count that I would have to redo my linux builds, and since this doesn't actually fix anything it's not really worth my redoing my linux builds atm, or anyone elses who may depend on this.

I'll be sure to keep this in mind for when we have a proper reason for upgrading however.

**Comment by Defman21** [comment]
Are you still able to create an image from 12.04? I get a lot of "404 Not Found" errors when installing packages.

**Comment by Naatan** [comment]
Yeah works fine for me. Perhaps your geographical location causes it to using a mirror that is incomplete?

**Comment by Defman21** [comment]
IIRC apt uses archive.ubuntu.com, not ru.archive.ubuntu.com.

**Comment by Defman21** [comment]
Seems like apt-get update doesn't work properly for me. There's the `curl 7.22.0-3ubuntu4.15`, but not `curl 7.22.0-3ubuntu4.14`

**Pull request closed without merging**
