### PR TITLE
schemes: handle python docstrings separately

### PR DESCRIPTION
**Pull request by kernc**
Color Python docstrings (triple-double-quoted strings as per [PEP-257](https://www.python.org/dev/peps/pep-0257/#specification)) differently than normal strings. Docstrings are closer to comments than strings anyway.

This is [not](https://community.activestate.com/forum-topic/how-edit-language-specifi) [a](https://community.activestate.com/forum-topic/where-to-find-komodo-edit) [lone](https://community.activestate.com/forum-topic/scintilla-integration) [request](https://community.activestate.com/node/9711).

Kudos on making it so trivial to extend! :+1:

### CODE REVIEW

**Comment by Naatan** [comment]
This seems incomplete to me. You're just identifying a docstring differently, but not doing anything with it. @mitchell-as can you comment on this? It's not my area of expertise.

**Comment by mitchell-as** [comment]
Correct, you are specifying that 'docstrings' be colored differently than normal strings, but you are not specifying the default color to use. Before we can consider merging this, you'd have to modify https://github.com/Komodo/komodo-color-schemes/blob/master/templates/common.p.py#L179 by adding a `'Python'` key and defining a `'fore'` color for `'docstring'`s.

**Comment by kernc** [comment]
Had the preview example snippet contained a docstring (along with all other common token types!), I would have noticed something odd. :smile: 

How's this?

**Comment by Naatan** [comment]
@mitchell-as can you review this? Note his follow-up PR is on a different repo, since the scheme files are defined outside the main repo.

Also, wouldn't this also turn the following into a docstring (ie. color it as a comment):

```
foo = """bar"""
```

That would be undesirable. 

Ie. what I'm getting at is

```
"""This is a docstring"""
foo = """this is not"""
```

I don't think this PR covers that use-case.

**Comment by mitchell-as** [comment]
@nathanr Correct. All triple-quoted-strings would wind up being coloured as comments. I don't think we want this.

**Comment by kernc** [comment]
All triple-**double-quoted** strings would wind up as docstrings, which
were set colored as comments by default, yes. Are you implying only the
latter is inappropriate, and they should instead by default be colored as
strings? Because anything more (i.e. distinguishing between real docstrings
and just triple-double-quoted strings) is impossible at the lexer level.

**Comment by Naatan** [comment]
Those docstrings are basically strings (multi-line strings), python docstrings are just appropriating them differently by using them as "comments". They are in fact strings, that are used as comments.

If it is in fact impossible to differentiate between the two use-cases then I would say it is not feasible to color them differently, and would in fact weigh in that direction already even if it were possible, because to the Python interpreter it is a string regardless.

**Comment by kernc** [comment]
Indeed. So they are colored as strings by default, but anyone is able to override that per preference. Is this ok?

**Comment by Naatan** [comment]
I think that's acceptable. But I don't think this PR is complete yet, koScintillaSchemeService has no notion of "docstrings" so even though they are defined they will not be passed to Scintilla (I think).

I think you'll either want to get Komodo Edit building so you can test this on your system or you should file an enhancement request and link to these commits to help it along.

**Comment by kernc** [comment]
This worked for me from the minute of first edit! Nothing to build here. :smiley:

**Comment by Naatan** [comment]
Just going over this again, because of aforementioned reasons (them all being either comments or docblocks) I'm going to close this PR. You could easily create a Python language derivative that has this change if you desire it, but I don't think this is a sensible change for a default Komodo install.

**Pull request closed without merging**
