### PR TITLE
Fixed #634

### LINKED ISSUE #634: Suggestion for Javascript keywords and reserved names
I'd like to suggest that you change the code starting line 170 of `src/python-sitelib/langinfo_prog.py` to:

```
    # These are the keywords that are used in most JavaScript environments.
    common_keywords = set([
                          "arguments",
                          "await",
                          "break",
                          "case",
                          "catch",
                          "class",
                          "const",
                          "continue",
                          "debugger",
                          "default",
                          "delete",
                          "do",
                          "else",
                          "enum",
                          "eval",
                          "export",
                          "extends",
                          "false",
                          "finally",
                          "for",
                          "function",
                          "if",
                          "implements",
                          "import",
                          "in",
                          "instanceof",
                          "interface",
                          "let",
                          "new",
                          "null",
                          "of",
                          "package",
                          "private",
                          "protected",
                          "public",
                          "return",
                          "static",
                          "super",
                          "switch",
                          "this",
                          "throw",
                          "true",
                          "try",
                          "typeof",
                          "var",
                          "void",
                          "while",
                          "with",
                          "yield"
                          ])
    keywords = common_keywords.union(
                # Additional JavaScript reserved keywords.
                set([
                    "Infinity",
                    "NaN",
                    "abstract",
                    "boolean",
                    "break",
                    "byte",
                    "case",
                    "catch",
                    "char",
                    "class",
                    "const",
                    "continue",
                    "debugger",
                    "default",
                    "delete",
                    "do",
                    "double",
                    "else",
                    "enum",
                    "export",
                    "extends",
                    "false",
                    "final",
                    "finally",
                    "float",
                    "for",
                    "function",
                    "goto",
                    "if",
                    "implements",
                    "import",
                    "in",
                    "instanceof",
                    "int",
                    "interface",
                    "long",
                    "native",
                    "new",
                    "null",
                    "package",
                    "private",
                    "protected",
                    "public",
                    "return",
                    "short",
                    "static",
                    "super",
                    "switch",
                    "synchronized",
                    "this",
                    "throw",
                    "throws",
                    "transient",
                    "true",
                    "try",
                    "typeof",
                    "undefined",
                    "var",
                    "void",
                    "volatile",
                    "while",
                    "with"
                  ]))
```

This is based on information at https://mathiasbynens.be/notes/reserved-keywords and some tests that I performed with the attached code at the end. The reason for this is because there appear to some words missing and the current lists would seem to make maintenance difficult; having the complete lists for keywords and reserved names, which you are making `unique` and then performing a `union` upon should help in future. The downside is that there may be a few duplicates between lists and therefore a few extra name entries. I hope that you find this information of use.

```
/*jshint devel:true */

(function () {
  'use strict';

  // These are the keywords that are used in most JavaScript environments.
  var keywords = [
      'break',
      'case',
      'catch',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'else',
      'export',
      'false',
      'finally',
      'for',
      'function',
      'if',
      'import',
      'in',
      'instanceof',
      'let',
      'new',
      'null',
      'of',
      'return',
      'switch',
      'this',
      'throw',
      'true',
      'try',
      'typeof',
      'undefined',
      'var',
      'void',
      'while',
      'with',
      'yield'
    ],

    // Additional JavaScript reserved keywords.
    reserved = [
      'abstract',
      'arguments',
      'boolean',
      'byte',
      'char',
      'class',
      'double',
      'enum',
      'eval',
      'extends',
      'final',
      'float',
      'goto',
      'implements',
      'int',
      'interface',
      'long',
      'native',
      'package',
      'private',
      'protected',
      'public',
      'short',
      'static',
      'super',
      'synchronized',
      'throws',
      'transient',
      'volatile'
    ],

    // ES3 Reserved Property Names
    es3rpn = [
      'abstract',
      'boolean',
      'break',
      'byte',
      'case',
      'catch',
      'char',
      'class',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'double',
      'else',
      'enum',
      'export',
      'extends',
      'false',
      'final',
      'finally',
      'float',
      'for',
      'function',
      'goto',
      'if',
      'implements',
      'import',
      'in',
      'instanceof',
      'int',
      'interface',
      'long',
      'native',
      'new',
      'null',
      'package',
      'private',
      'protected',
      'public',
      'return',
      'short',
      'static',
      'super',
      'switch',
      'synchronized',
      'this',
      'throw',
      'throws',
      'transient',
      'true',
      'try',
      'typeof',
      'var',
      'void',
      'volatile',
      'while',
      'with'
    ],

    // Actual ES3 reserved words.
    /*
    es3 = [
      'abstract',
      'boolean',
      'break',
      'byte',
      'case',
      'catch',
      'char',
      'class',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'double',
      'else',
      'enum',
      'export',
      'extends',
      'false',
      'final',
      'finally',
      'float',
      'for',
      'function',
      'goto',
      'if',
      'implements',
      'import',
      'in',
      'instanceof',
      'int',
      'interface',
      'long',
      'native',
      'new',
      'null',
      'package',
      'private',
      'protected',
      'public',
      'return',
      'short',
      'static',
      'super',
      'switch',
      'synchronized',
      'this',
      'throw',
      'throws',
      'transient',
      'true',
      'try',
      'typeof',
      'var',
      'void',
      'volatile',
      'while',
      'with'
    ],
    */

    // Actual ES5 reserved words.
    /*
    es5 = [
      'arguments',
      'break',
      'case',
      'catch',
      'class',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'else',
      'enum',
      'eval',
      'export',
      'extends',
      'false',
      'finally',
      'for',
      'function',
      'if',
      'implements',
      'import',
      'in',
      'instanceof',
      'interface',
      'let',
      'new',
      'null',
      'package',
      'private',
      'protected',
      'public',
      'return',
      'static',
      'super',
      'switch',
      'this',
      'throw',
      'true',
      'try',
      'typeof',
      'var',
      'void',
      'while',
      'with',
      'yield'
    ],
    */

    // Actual ES6 reserved words.
    es6 = [
      'arguments',
      'await',
      'break',
      'case',
      'catch',
      'class',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'else',
      'enum',
      'eval',
      'export',
      'extends',
      'false',
      'finally',
      'for',
      'function',
      'if',
      'implements',
      'import',
      'in',
      'instanceof',
      'interface',
      'let',
      'new',
      'null',
      'of',
      'package',
      'private',
      'protected',
      'public',
      'return',
      'static',
      'super',
      'switch',
      'this',
      'throw',
      'true',
      'try',
      'typeof',
      'var',
      'void',
      'while',
      'with',
      'yield',
    ],

    strictReserved = [
      'Infinity',
      'NaN',
      'undefined'
    ],

    // Union of the two Komodi lists.
    komodoSet,
    komodoAll,

    // Results.
    missingES6,
    missingES3Reserved,
    missingES6Strict,
    missingReserved,
    additional,
    suggestedKeywords = es6.slice(),
    suggestedReserved = es3rpn.concat(strictReserved).sort(),
    sugestedSet,
    suggestedAll,
    missing;

  // Union of the three suggested lists.
  sugestedSet = new Set(suggestedKeywords);
  suggestedReserved.forEach(function (name) {
    sugestedSet.add(name);
  });

  suggestedAll = Array.from(sugestedSet).sort();

  // Union of the two Komodi lists.
  komodoSet = new Set(keywords);
  reserved.forEach(function (name) {
    komodoSet.add(name);
  });

  komodoAll = Array.from(komodoSet).sort();

  // Missing ES6 from Komodo
  missingES6 = es6.reduce(function (acc, keyword) {
    if (keywords.indexOf(keyword) === -1) {
      acc.push(keyword);
    }

    return acc;
  }, []);

  // Missing ES3 reserved from Komodo
  missingES3Reserved = es3rpn.reduce(function (acc, keyword) {
    if (reserved.indexOf(keyword) === -1) {
      acc.push(keyword);
    }

    return acc;
  }, []);

  // Missing ES6 strict from Komodo
  missingES6Strict = strictReserved.reduce(function (acc, keyword) {
    if (reserved.indexOf(keyword) === -1) {
      acc.push(keyword);
    }

    return acc;
  }, []);

  missingReserved = missingES3Reserved.concat(missingES6Strict).sort();

  // Additional to Komodo
  additional = komodoAll.reduce(function (acc, keyword) {
    if (suggestedAll.indexOf(keyword) === -1) {
      acc.push(keyword);
    }

    return acc;
  }, []);

  // Additional to Komodo
  missing = suggestedAll.reduce(function (acc, keyword) {
    if (komodoAll.indexOf(keyword) === -1) {
      acc.push(keyword);
    }

    return acc;
  }, []);

  //console.log('missingES6', JSON.stringify(missingES6, null, 2));
  //console.log('missingES3Reserved', JSON.stringify(missingES3Reserved, null, 2));
  //console.log('missingES6Strict', JSON.stringify(missingES6Strict, null, 2));
  //console.log('missingReserved', JSON.stringify(missingReserved, null, 2));
  //console.log('additional', JSON.stringify(additional, null, 2));
  //console.log('missing', JSON.stringify(missing, null, 2));
  console.log('suggestedKeywords', JSON.stringify(suggestedKeywords, null, 2));
  console.log('suggestedReserved', JSON.stringify(suggestedReserved, null, 2));
}());

```

### PR DESCRIPTION
**Pull request by Defman21**
Thanks a lot to @Xotic750
I've tested those changes and they works fine! :)

### CODE REVIEW

**Comment by Defman21** [comment]
Ahh crap, submodule's commits were changed... Is it okay?

**Comment by Naatan** [comment]
Nope, please remove the submodule change :)

**Comment by Defman21** [comment]
Can you help me with doing it?

**Comment by Naatan** [comment]
You'll have to redo your PR. Just don't commit things that you don't want to commit .. ;)

**Comment by cgchoffman** [comment]
@Defman21 if there is a submodules change in your commit it's probably becuase you haven't run `git submodule update` since a submodule update went in.

**Comment by Naatan** [comment]
Or the submodules may be behind (I don't think so cause I recently updated them), but regardless this should not be part of any commit that isn't related to those submodules.

**Comment by Defman21** [comment]
I'll send an another PR. This is completely broken :(

**Pull request closed without merging**
