### PR TITLE
Fixed building proccess for non-as network

### LINKED ISSUE #2290: python build.py all trying to download the wrong mozilla base
For some reason, it's trying to download the top branch:

```
target: all
target: src
running 'wget -t 5 -T 30 --progress=dot:mega -O /home/defman/projects/komodo/source/mozilla/mozilla-release.hg http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg'
--2017-01-27 20:45:40--  http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg
Resolving ftp.mozilla.org (ftp.mozilla.org)... 52.85.214.203
Connecting to ftp.mozilla.org (ftp.mozilla.org)|52.85.214.203|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-27 20:45:40 ERROR 404: Not Found.

Traceback (most recent call last):
  File "build.py", line 2959, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2955, in main
    return build(args)
  File "build.py", line 2779, in build
    newArgv = targetFunc(argv)
  File "build.py", line 2460, in target_all
    target_src()
  File "build.py", line 2110, in target_src
    _run("wget -t 5 -T 30 --progress=dot:mega -O %s %s" % (bundleFile, bundleURL), log.info)
  File "build.py", line 231, in _run
    raise OSError("error running '%s': %r" % (cmd, status))
OSError: error running 'wget -t 5 -T 30 --progress=dot:mega -O /home/defman/projects/komodo/source/mozilla/mozilla-release.hg http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg': 8
```

Here's my config:

```
blessed = False
buildDir = '/home/defman/projects/komodo/source/mozilla/build'
buildOpt = []
buildTag = None
buildType = 'release'
changenum = 0
compiler = None
configureOptions = ['-k', '10.10']
enableMar = True
gcc = '/usr/bin/gcc'
gxx = '/usr/bin/g++'
jsStandalone = False
komodoCommaVersion = '10,10'
komodoUndottedVersion = '1010'
komodoVersion = '10.10'
mozBuildExtensions = []
mozObjDir = 'ko-rel'
mozSrcHgRepo = '3500'
mozSrcHgTag = None
mozSrcName = 'moz3500'
mozSrcScheme = '3500'
mozSrcType = 'hg'
mozVer = 35.0
mozconfig = "# Options for 'configure' (same as command-line options).\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/ko-rel\nexport CC=/usr/bin/gcc\nexport CXX=/usr/bin/g++\nac_add_options --enable-stdcxx-compat\nac_add_options --disable-gstreamer\nac_add_options --enable-gold\nac_add_options --enable-help-viewer\nac_add_options --disable-tests\nac_add_options --enable-optimize\nac_add_options --disable-debug\nac_add_options --enable-application=komodo\n"
patchesDirs = ['patches-new']
platform = 'linux-x86_64'
platinfo = {'name': 'linux-x86_64', 'libc': 'libc6', 'distro_codename': 'loki', 'libcpp': 'libcpp6', 'glibc_ver': '2.23', 'arch': 'x86_64', 'distro_ver': '0.4', 'distro_desc': 'elementary OS 0.4 Loki', 'os': 'linux', 'glibc': 'glibc', 'os_ver': '4.4.0', 'distro': 'elementary'}
pyVer = '2.7'
python = '/home/defman/projects/komodo/source/mozilla/prebuilt/python2.7/linux-x86_64/bin/python'
pythonVersion = '2.7'
srcTreeName = 'moz3500-ko10.10'
stripBuild = False
universal = False
withCrashReportSymbols = False
withPGOCollection = False
withPGOGeneration = False
```

### PR DESCRIPTION
**Pull request by Defman21**
Signed-off-by: Defman21 <i@defman.me>

fixed #2290

### CODE REVIEW

**Comment by Defman21** [comment]
To clarify what's going now with this change:

The build process retrieves the json contains relative urls to hg bundles, looks for `release/%treeName` key in it, gets path to the bzip2 bundle (this is the smallest one and it works with `hg unbundle` unlike streams) and downloads it.

**Comment by Defman21** [comment]
I haven't tested the `mozilla-release` one, but it works fine for me with `comm-central`.

**Comment by Defman21** [comment]
Works fine with the `mozilla-release` as well.

**Comment by Naatan** [comment]
Thanks @Defman21 !

**Pull request merged**
